services:
  - type: web
    name: kmv-carrot-knowledge-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: BOT_TOKEN
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: ADMIN_IDS
        sync: false
      - key: WEBHOOK_HOST
        fromService:
          type: web
          name: kmv-carrot-knowledge-bot
          envVarKey: RENDER_EXTERNAL_URL
      - key: WEBHOOK_PATH
        value: /webhook
      - key: WEBAPP_HOST
        value: 0.0.0.0
      - key: PORT
        value: 8443
      - key: DB_DIR
        value: /opt/render/project/src/data
      - key: DB_BACKUP_DIR
        value: /opt/render/project/src/data/backups
      - key: LOG_DIR
        value: /opt/render/project/src/logs
    healthCheckPath: /health
    autoDeploy: true 