services:
  - type: web
    name: kmv-carrot-knowledge-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --worker-class aiohttp.worker.GunicornWebWorker --workers 4 --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: BOT_TOKEN
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: ADMIN_IDS
        sync: false
      - key: WEBHOOK_HOST
        fromService:
          type: web
          name: kmv-carrot-knowledge-bot
          envVarKey: RENDER_EXTERNAL_URL
      - key: WEBHOOK_PATH
        value: /webhook
      - key: WEBAPP_HOST
        value: 0.0.0.0
      - key: WEBAPP_PORT
        value: $PORT
      - key: WEBHOOK_SSL_CERT
        value: /etc/ssl/certs/ca-certificates.crt  # System SSL certificates
    healthCheckPath: /health
    autoDeploy: true 