services:
  - type: web
    name: kmv-carrot-knowledge-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --worker-class aiohttp.worker.GunicornWebWorker --workers 4 --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: WEBHOOK_PATH
        value: /webhook
      - key: ENVIRONMENT
        value: production
      - key: ADMIN_USER_IDS
        sync: false
    healthCheckPath: /health
    autoDeploy: true 